{{- if .Values.oathkeeper.managedAccessRules }}
{{- if .Values.maester.enabled -}}
{{- fail "Both `managedAccessRules` and `maester.enabled` cannot be set to true at the same time" }}
{{- end -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oathkeeper.fullname" . }}-rules
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "oathkeeper.labels" . | indent 4 }}
data:
  "access-rules.json": |-
{{ .Values.oathkeeper.accessRules | default "[]" | indent 4 }}
{{- end }}
